default_language_version:
    python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==21.9.2
          - flake8-comprehensions==3.6.1
          - flake8-deprecated==1.3
          - flake8-docstrings==1.6.0
          - flake8-implicit-str-concat==0.2.0
          - flake8-keyword-arguments==0.1.0
          - flake8-print==4.0.0
          - flake8-sfs==0.0.3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML==5.4.10
          - types-setuptools==57.4.0
          - types-requests==2.25.9
          - types-python-dateutil==2.8.19
        exclude: tests
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.9.0
    hooks:
      - id: pip-compile
        name: pip-compile requirements.txt
        files: setup.cfg
        args: [setup.cfg, -q, -o, requirements/requirements.txt]
      - id: pip-compile
        name: pip-compile requirements-docs.txt
        files: requirements/docs.in
        args: [ requirements/docs.in, -q, -o,
                requirements/requirements-docs.txt ]
      - id: pip-compile
        name: pip-compile requirements-tests.txt
        files: requirements/tests.in
        args: [requirements/tests.in, -q, -o,
               requirements/requirements-tests.txt]
      - id: pip-compile
        name: pip-compile requirements-dev.txt
        files: requirements/(dev.in|docs.in|tests.in|requirements.txt)
        args: [requirements/dev.in, -q, -o,
               requirements/requirements-dev.txt]
