iso3: eth
codab:
  hdx_dataset_name: ETH Administrative Divisions Shapefiles.zip
  layer_base_name: eth_admbnda_adm{admin_level}_csa_bofed_20201008.shp
  admin_level_max: 3
  admin0_name: eth_admbnda_adm0_csa_bofedb_itos_2021
fewsnet:
  region_name: east-africa
glofas:
  reporting_points:
  - name: Abetlti
    lon: 37.55
    lat: 8.25
  - name: Adaitu
    lon: 40.65
    lat: 11.15
  - name: Asetndabo
    lon: 37.15
    lat: 7.75
  - name: Awash Wenz At Hombole
    lon: 38.85
    lat: 8.35
  - name: Awash Wenz At Melka Kuntire
    lon: 38.55
    lat: 8.75
  - name: Bahir Dar
    lon: 37.35
    lat: 11.55
  - name: Eddiem
    lon: 34.95
    lat: 11.25
  - name: Gambella
    lon: 34.65
    lat: 8.15
  - name: Melka Sedi
    lon: 40.15
    lat: 9.15
  - name: Metahara
    lon: 39.95
    lat: 8.85
  - name: Na 1
    lon: 42.05
    lat: 4.75
  - name: Na 2
    lon: 44.85
    lat: 5.05
  - name: Na 3
    lon: 44.45
    lat: 5.45
  - name: Na 4
    lon: 44.05
    lat: 5.65
  - name: Na 5
    lon: 43.05
    lat: 6.05
  - name: Nr. Addis Zemen
    lon: 37.75
    lat: 12.05
  - name: Nr. Bahir Dar
    lon: 37.65
    lat: 11.85
  - name: Nr. Kessie
    lon: 38.15
    lat: 10.05
  - name: Nr. Marawi
    lon: 37.05
    lat: 11.35
  - name: Omo River Delta
    lon: 36.05
    lat: 4.85
  - name: Sekta
    lon: 36.75
    lat: 7.65
  - name: Shetbe
    lon: 36.45
    lat: 7.45
  - name: Tendaho
    lon: 40.95
    lat: 11.65
  - name: Woltkite 1
    lon: 37.75
    lat: 8.25
  - name: Woltkite 2
    lon: 37.55
    lat: 8.35
usgs_ndvi:
  area_name: east-africa
