iso3: bfa
codab:
  hdx_dataset_name: bfa_adm_igb_20200323_SHP.zip
  layer_base_name: bfa_admbnda_adm{admin_level}_igb_20200323.shp
  layer_base_admin_levels: [0,1,2,3]
fewsnet:
  region_name: west-africa
