iso3: bfa
codab:
  hdx_dataset_name: bfa_adm_igb_20200323_SHP.zip
  layer_base_name: bfa_admbnda_adm{admin_level}_igb_20200323.shp
  admin_level_max: 3
fewsnet:
  region_name: west-africa
glofas:
  reporting_points:
  - id: G4887
    name: Bassieri
    lon: 0.35
    lat: 12.75
  - id: G4900
    name: Sebba
    lon: 0.45
    lat: 13.45
  - id: G4915
    name: Liptougou
    lon: 0.35
    lat: 13.25
