iso3: cod
codab:
  hdx_dataset_name: cod_admbnda_rgc_itos_20190911_SHP.zip
  layer_base_name: cod_admbnda_adm{admin_level}_rgc_itos_20190911.shp
  admin_level_max: 1
  # this is the name of the adm2 layer
  custom_layer_names:
    - cod_admbnda_adm2_rgc_20190911.shp
fewsnet:
  region_name: southern-africa
