iso3: mwi
codab:
  hdx_address: malawi-administrative-level-0-3-boundaries
  hdx_dataset_name: mwi_adm_nso_20181016_SHP.zip
  layer_base_name: mwi_admbnda_adm{admin_level}_nso_20181016.shp
  admin_level_max: 3
ecmwf_realtime:
  number_points_mapping: 384
  geoboundaries_mapping:
    north: -4.8
    south: -17.2
    west: 32.8
    east: 37.2
