iso3: mwi
codab:
  hdx_dataset_name: mwi_adm_nso_20181016_SHP.zip
  layer_base_name: mwi_admbnda_adm{admin_level}_nso_20181016.shp
  layer_base_admin_levels: [0,1,2,3]
fewsnet:
  region_name: southern-africa
