iso3: mwi
codab:
  hdx_dataset_name: mwi_adm_nso_20181016_SHP.zip
  layer_base_name: mwi_admbnda_adm{admin_level}_nso_20181016.shp
  admin_level_max: 3
fewsnet:
  region_name: southern-africa
glofas:
  reporting_points:
  - id: G1277
    name: Phewzi 65312414
    lon: 33.95
    lat: -10.95
  - id: G1307
    name: S53 Roadbridge 65312601
    lon: 34.15
    lat: -12.85
  - id: G1724
    name: Na
    lon: 35.05
    lat: -16.45
  - id: G2001
    name: Na
    lon: 34.95
    lat: -16.25
  - id: G5669
    name: Liwonde
    lon: 35.25
    lat: -15.05
  - id: G5670
    name: Sinoya South
    lon: 35.25
    lat: -16.25
  - id: G5694
    name: Chikwawa
    lon: 34.85
    lat: -16.05
